# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gk
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Build agent
      run: |
          cd cmd/agent
          go build -buildvcs=false -o agent
    
    - name: Build server
      run: |
          cd cmd/server
          go build -buildvcs=false -o server

    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  upload-release:
    runs-on: ubuntu-latest
    needs: [ build-macos, build-linux, build-windows ]

    steps:
      - uses: actions/checkout@v4
      - name: create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: uploads
      - name: upload macos
        id: upload-macos
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/macos.zip
          asset_name: macos.zip
          asset_content_type: application/zip
      - name: upload linux
        id: upload-linux
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/linux.zip
          asset_name: linux.zip
          asset_content_type: application/zip
      - name: upload windows
        id: upload-windows
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/windows.zip
          asset_name: windows.zip
          asset_content_type: application/zip

  build-macos:
    runs-on: macOS-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build agent
        run: |
          cd cmd/agent
          go build -ldflags "-X main.buildVersion=$(date +'%Y%m%d') -X main.buildDate=$(date +'%Y-%m-%dT%H:%M:%S')" -buildvcs=false
      - name: zip macos artifact
        run: |
          zip -r macos out
      - name: upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploads
          path: macos.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build agent
        run: |
          cd cmd/agent
          go build -ldflags "-X main.buildVersion=$(date +'%Y%m%d') -X main.buildDate=$(date +'%Y-%m-%dT%H:%M:%S')" -buildvcs=false
      - name: zip linux artifact
        run: |
          zip -r linux out
      - name: upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploads
          path: linux.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build agent
        run: |
          cd cmd/agent
          go build -ldflags "-X main.buildVersion=$(date +'%Y%m%d') -X main.buildDate=$(date +'%Y-%m-%dT%H:%M:%S')" -buildvcs=false
      - name: zip win artifact
        run: |
          powershell Compress-Archive out windows.zip
      - name: upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploads
          path: windows.zip